production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5m 'pg'

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: park_app_development

test:
  <<: *default
  database: park_app_test

production:
  <<: *default
  database: park_app_production
  username: park_app
  password: <%= ENV['PARK_APP_DATABASE_PASSWORD'] %>
